// window : window is an global object which contains all the methods of javascript 
// A global variable, window, representing the window in which the script is running, is exposed to JavaScript code.
//in js everythings are comes under the window object
// console.log(window);
// window.console.log();  // open with liveserver and check in console panel


// ------------------------------------------------------------------------------------------------
// Introduction to the DOM
// The Document Object Model (DOM) is the data representation of the objects that comprise the structure and content of a document on the web. This guide will introduce the DOM, look at how the DOM represents an HTML document in memory and how to use APIs to create web content and applications.

// What is the DOM?
// The Document Object Model (DOM) is a programming interface for web documents. It represents the page so that programs can change the document structure, style, and content. The DOM represents the document as nodes and objects; that way, programming languages can interact with the page.

// Document Object Model (DOM) : it is the simple representation of html page as a tree form

// document.body.style.background = "yellow";    // open with liveserver 

// ------------------------------------------------------------------------------------------------
// BOM (Browser Object Model ) : the Browser Object Model represents the additional object provided by the browser (Host environment) for working with everything except the browser

//  The functions alert/confirm/prompt are also a part of BOM
// alert("Hello");
// location.href = "https://www.w3schools.com/js/js_window.asp";  //it will open this link directoly





